# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melvyn_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='co_author',
            field=models.CharField(default='Null', max_length=20),
            preserve_default=False,
        ),
    ]
