# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('melvyn_blog', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=b'illustrations'),
        ),
    ]
