# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melvyn_blog', '0006_auto_20160522_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
